### PR TITLE
Add new textures 

### PR DESCRIPTION
**Pull request by Skiner111**
Can someone add new textures?

### CODE REVIEW

**Comment by KuriKai** [comment]
a-brown1.png, a-vine4.png are good and I can pull them if you remove the others from the pull request. as skinlow, a-camo1 and a-camo2 need some work to make them look more like the originals

**Comment by Skiner111** [comment]
> a-brown1.png, a-vine4.png are good and I can pull them if you remove the others from the pull request. as skinlow, a-camo1 and a-camo2 need some work to make them look more like the originals
I understood, could you explain how to remove unnecessary textures from the pull request, I just did not find a way to remove them?

**Comment by Skiner111** [comment]
It is possible to delete commits and their history ?

**Comment by Skiner111** [comment]
I remade a-camo1 and a-camo2 textures
Screenshot_Doom_20190517_171229
Screenshot_Doom_20190517_164726
Screenshot_Doom_20190517_171257
Screenshot_Doom_20190517_164835
Screenshot_Doom_20190517_171206
Screenshot_Doom_20190517_173228

**Comment by KuriKai** [comment]
can you make a-camo1.png have the same patern?
and I jsut noticed on a-brown1.png that the bevel in the top middle and bottom middle needs a bit of tweaking as the bevels are overlapping each other

**Comment by Skiner111** [comment]
I did not understand what to do with a-camo1. Make closer to original?
I remade a-brown 1 and remove bevel
Screenshot_Doom_20190518_201833

**Comment by Skiner111** [comment]
I did't quite understand what to do with a-camo texture. Make it similar to original texture ?
I remade a-brown1 texture
Screenshot_Doom_20190518_232508
Screenshot_Doom_20190518_232522

**Comment by Skiner111** [comment]
Updated a-camo1,a-camo-2 textures
Screenshot_Doom_20190519_155708
Screenshot_Doom_20190519_155621

**Comment by Skiner111** [comment]
Updated a-camo1 and a-camo2 in last commit
Screenshot_Doom_20190520_165711
Screenshot_Doom_20190520_165819

**Comment by Skiner111** [comment]
Can you add new textures ?

**Comment by Skiner111** [comment]
Test
Duplicate of 61c89768d666cebc5254604e4c38b46552aa75a6#

**Pull request merged**
