### PR TITLE
Doom 2 Skinlow Texture

### PR DESCRIPTION
**Pull request by Skiner111**

### CODE REVIEW

**Comment by Skiner111** [comment]
Screenshot_Doom_20190611_200447
Screenshot_Doom_20190611_200605

**Comment by Skiner111** [comment]
Screenshot_Doom_20190611_202702
Screenshot_Doom_20190611_202728

**Comment by KuriKai** [comment]
Are you able to provide it in higher detail?, also the bezel light is too strong, bolts are too big, and the wood is the wrong colour
SKINLOW

**Comment by Skiner111** [comment]
> Are you able to provide it in higher detail?, also the bezel light is too strong, bolts are too big, and the wood is the wrong colour
> SKINLOW

In general, i redid the skinlow texture. Maybe i will try make skin texture similar to original
Screenshot_Doom_20190614_200113
Screenshot_Doom_20190614_200148

**Comment by Skiner111** [comment]
Screenshot_Doom_20190615_174552
Screenshot_Doom_20190615_174619
Screenshot_Doom_20190615_174707

**Comment by te4monster** [comment]
JMHO, but I think the wood needs to be more raw and untreated or finished. The original texture appears to be rough-hewn and weathered. At the moment, with the later one especially, the wood, in colour and finish, looks very much like it's been heavily polished, dyed and waxed. 

As to the skin, I think you've zoomed in too much to get minor wrinkles on the skin. In the original texture those dark marks look more like hairs. That wouldn't be to scale, but neither would the wrinkles as they appear on the later version of yours.

**Comment by Skiner111** [comment]
> JMHO, but I think the wood needs to be more raw and untreated or finished. The original texture appears to be rough-hewn and weathered. At the moment, with the later one especially, the wood, in colour and finish, looks very much like it's been heavily polished, dyed and waxed.
> 
> As to the skin, I think you've zoomed in too much to get minor wrinkles on the skin. In the original texture those dark marks look more like hairs. That wouldn't be to scale, but neither would the wrinkles as they appear on the later version of yours.

Thanks for the advice, I will try to fix it.

**Comment by Skiner111** [comment]
Updated skinlow texture
Screenshot_Doom_20190625_102115
Screenshot_Doom_20190625_102127
Screenshot_Doom_20190625_102155

**Comment by KuriKai** [comment]
needs more work to match closer to the original texture

**Pull request closed without merging**
